export enum ResourceTargetType {
  UNSPECIFIED = 'RESOURCE_TARGET_TYPE_UNSPECIFIED',
  SONG_PERFORMANCE = 'RESOURCE_TARGET_TYPE_SONG_PERFORMANCE',
  ARTIST_PROFILE = 'RESOURCE_TARGET_TYPE_ARTIST_PROFILE',
  SONG = 'RESOURCE_TARGET_TYPE_SONG',
}
