// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: bst/v1/studio_review_service.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { StudioReview } from "./location";

export const protobufPackage = "bst.v1";

export interface CreateStudioReviewRequest {
  studioId: number;
  comment: string;
}

export interface CreateStudioReviewResponse {
  review: StudioReview | undefined;
}

export interface ListStudioReviewsRequest {
  studioId: number;
  pageSize: number;
  pageToken: number;
}

export interface ListStudioReviewsResponse {
  reviews: StudioReview[];
  nextPageToken: string;
  totalSize: number;
}

export interface DeleteStudioReviewRequest {
  studioId: number;
  reviewId: number;
}

export interface DeleteStudioReviewResponse {
  success: boolean;
}

function createBaseCreateStudioReviewRequest(): CreateStudioReviewRequest {
  return { studioId: 0, comment: "" };
}

export const CreateStudioReviewRequest = {
  encode(message: CreateStudioReviewRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.studioId !== 0) {
      writer.uint32(8).int32(message.studioId);
    }
    if (message.comment !== "") {
      writer.uint32(18).string(message.comment);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateStudioReviewRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateStudioReviewRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.studioId = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.comment = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateStudioReviewRequest {
    return {
      studioId: isSet(object.studioId) ? globalThis.Number(object.studioId) : 0,
      comment: isSet(object.comment) ? globalThis.String(object.comment) : "",
    };
  },

  toJSON(message: CreateStudioReviewRequest): unknown {
    const obj: any = {};
    if (message.studioId !== 0) {
      obj.studioId = Math.round(message.studioId);
    }
    if (message.comment !== "") {
      obj.comment = message.comment;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateStudioReviewRequest>, I>>(base?: I): CreateStudioReviewRequest {
    return CreateStudioReviewRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateStudioReviewRequest>, I>>(object: I): CreateStudioReviewRequest {
    const message = createBaseCreateStudioReviewRequest();
    message.studioId = object.studioId ?? 0;
    message.comment = object.comment ?? "";
    return message;
  },
};

function createBaseCreateStudioReviewResponse(): CreateStudioReviewResponse {
  return { review: undefined };
}

export const CreateStudioReviewResponse = {
  encode(message: CreateStudioReviewResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.review !== undefined) {
      StudioReview.encode(message.review, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateStudioReviewResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateStudioReviewResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.review = StudioReview.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateStudioReviewResponse {
    return { review: isSet(object.review) ? StudioReview.fromJSON(object.review) : undefined };
  },

  toJSON(message: CreateStudioReviewResponse): unknown {
    const obj: any = {};
    if (message.review !== undefined) {
      obj.review = StudioReview.toJSON(message.review);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateStudioReviewResponse>, I>>(base?: I): CreateStudioReviewResponse {
    return CreateStudioReviewResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateStudioReviewResponse>, I>>(object: I): CreateStudioReviewResponse {
    const message = createBaseCreateStudioReviewResponse();
    message.review = (object.review !== undefined && object.review !== null)
      ? StudioReview.fromPartial(object.review)
      : undefined;
    return message;
  },
};

function createBaseListStudioReviewsRequest(): ListStudioReviewsRequest {
  return { studioId: 0, pageSize: 0, pageToken: 0 };
}

export const ListStudioReviewsRequest = {
  encode(message: ListStudioReviewsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.studioId !== 0) {
      writer.uint32(8).int32(message.studioId);
    }
    if (message.pageSize !== 0) {
      writer.uint32(16).int32(message.pageSize);
    }
    if (message.pageToken !== 0) {
      writer.uint32(24).int32(message.pageToken);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListStudioReviewsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListStudioReviewsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.studioId = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.pageToken = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListStudioReviewsRequest {
    return {
      studioId: isSet(object.studioId) ? globalThis.Number(object.studioId) : 0,
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : 0,
      pageToken: isSet(object.pageToken) ? globalThis.Number(object.pageToken) : 0,
    };
  },

  toJSON(message: ListStudioReviewsRequest): unknown {
    const obj: any = {};
    if (message.studioId !== 0) {
      obj.studioId = Math.round(message.studioId);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.pageToken !== 0) {
      obj.pageToken = Math.round(message.pageToken);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListStudioReviewsRequest>, I>>(base?: I): ListStudioReviewsRequest {
    return ListStudioReviewsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListStudioReviewsRequest>, I>>(object: I): ListStudioReviewsRequest {
    const message = createBaseListStudioReviewsRequest();
    message.studioId = object.studioId ?? 0;
    message.pageSize = object.pageSize ?? 0;
    message.pageToken = object.pageToken ?? 0;
    return message;
  },
};

function createBaseListStudioReviewsResponse(): ListStudioReviewsResponse {
  return { reviews: [], nextPageToken: "", totalSize: 0 };
}

export const ListStudioReviewsResponse = {
  encode(message: ListStudioReviewsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.reviews) {
      StudioReview.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.nextPageToken !== "") {
      writer.uint32(18).string(message.nextPageToken);
    }
    if (message.totalSize !== 0) {
      writer.uint32(24).int32(message.totalSize);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListStudioReviewsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListStudioReviewsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.reviews.push(StudioReview.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.nextPageToken = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.totalSize = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListStudioReviewsResponse {
    return {
      reviews: globalThis.Array.isArray(object?.reviews)
        ? object.reviews.map((e: any) => StudioReview.fromJSON(e))
        : [],
      nextPageToken: isSet(object.nextPageToken) ? globalThis.String(object.nextPageToken) : "",
      totalSize: isSet(object.totalSize) ? globalThis.Number(object.totalSize) : 0,
    };
  },

  toJSON(message: ListStudioReviewsResponse): unknown {
    const obj: any = {};
    if (message.reviews?.length) {
      obj.reviews = message.reviews.map((e) => StudioReview.toJSON(e));
    }
    if (message.nextPageToken !== "") {
      obj.nextPageToken = message.nextPageToken;
    }
    if (message.totalSize !== 0) {
      obj.totalSize = Math.round(message.totalSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListStudioReviewsResponse>, I>>(base?: I): ListStudioReviewsResponse {
    return ListStudioReviewsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListStudioReviewsResponse>, I>>(object: I): ListStudioReviewsResponse {
    const message = createBaseListStudioReviewsResponse();
    message.reviews = object.reviews?.map((e) => StudioReview.fromPartial(e)) || [];
    message.nextPageToken = object.nextPageToken ?? "";
    message.totalSize = object.totalSize ?? 0;
    return message;
  },
};

function createBaseDeleteStudioReviewRequest(): DeleteStudioReviewRequest {
  return { studioId: 0, reviewId: 0 };
}

export const DeleteStudioReviewRequest = {
  encode(message: DeleteStudioReviewRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.studioId !== 0) {
      writer.uint32(8).int32(message.studioId);
    }
    if (message.reviewId !== 0) {
      writer.uint32(16).int32(message.reviewId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeleteStudioReviewRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteStudioReviewRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.studioId = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.reviewId = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteStudioReviewRequest {
    return {
      studioId: isSet(object.studioId) ? globalThis.Number(object.studioId) : 0,
      reviewId: isSet(object.reviewId) ? globalThis.Number(object.reviewId) : 0,
    };
  },

  toJSON(message: DeleteStudioReviewRequest): unknown {
    const obj: any = {};
    if (message.studioId !== 0) {
      obj.studioId = Math.round(message.studioId);
    }
    if (message.reviewId !== 0) {
      obj.reviewId = Math.round(message.reviewId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteStudioReviewRequest>, I>>(base?: I): DeleteStudioReviewRequest {
    return DeleteStudioReviewRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteStudioReviewRequest>, I>>(object: I): DeleteStudioReviewRequest {
    const message = createBaseDeleteStudioReviewRequest();
    message.studioId = object.studioId ?? 0;
    message.reviewId = object.reviewId ?? 0;
    return message;
  },
};

function createBaseDeleteStudioReviewResponse(): DeleteStudioReviewResponse {
  return { success: false };
}

export const DeleteStudioReviewResponse = {
  encode(message: DeleteStudioReviewResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeleteStudioReviewResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteStudioReviewResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteStudioReviewResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: DeleteStudioReviewResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteStudioReviewResponse>, I>>(base?: I): DeleteStudioReviewResponse {
    return DeleteStudioReviewResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteStudioReviewResponse>, I>>(object: I): DeleteStudioReviewResponse {
    const message = createBaseDeleteStudioReviewResponse();
    message.success = object.success ?? false;
    return message;
  },
};

export interface StudioReviewService {
  /** POST /studios/{id}/reviews */
  CreateStudioReview(request: CreateStudioReviewRequest): Promise<CreateStudioReviewResponse>;
  /** GET /studios/{id}/reviews */
  ListStudioReviews(request: ListStudioReviewsRequest): Promise<ListStudioReviewsResponse>;
  /** DELETE /studios/{id}/reviews/{reviewId} */
  DeleteStudioReview(request: DeleteStudioReviewRequest): Promise<DeleteStudioReviewResponse>;
}

export const StudioReviewServiceServiceName = "bst.v1.StudioReviewService";
export class StudioReviewServiceClientImpl implements StudioReviewService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || StudioReviewServiceServiceName;
    this.rpc = rpc;
    this.CreateStudioReview = this.CreateStudioReview.bind(this);
    this.ListStudioReviews = this.ListStudioReviews.bind(this);
    this.DeleteStudioReview = this.DeleteStudioReview.bind(this);
  }
  CreateStudioReview(request: CreateStudioReviewRequest): Promise<CreateStudioReviewResponse> {
    const data = CreateStudioReviewRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateStudioReview", data);
    return promise.then((data) => CreateStudioReviewResponse.decode(_m0.Reader.create(data)));
  }

  ListStudioReviews(request: ListStudioReviewsRequest): Promise<ListStudioReviewsResponse> {
    const data = ListStudioReviewsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListStudioReviews", data);
    return promise.then((data) => ListStudioReviewsResponse.decode(_m0.Reader.create(data)));
  }

  DeleteStudioReview(request: DeleteStudioReviewRequest): Promise<DeleteStudioReviewResponse> {
    const data = DeleteStudioReviewRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteStudioReview", data);
    return promise.then((data) => DeleteStudioReviewResponse.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
